# Generated by Django 5.1 on 2024-08-13 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cookie_cutter_app', '0001_initial'),
        ('decoration_app', '0001_initial'),
        ('flavor_app', '0001_initial'),
        ('topping_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prev_purchased', models.BooleanField(default=False)),
                ('cookie_cutter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookie_cutter_app.cookiecutter')),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decoration_app.decoration')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flavor_app.flavor')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topping_app.topping')),
            ],
        ),
    ]
