# Generated by Django 5.1 on 2024-08-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_creation_app', '0002_alter_cookiecreation_decoration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiecreation',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
