# Generated by Django 5.1 on 2024-08-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_creation_app', '0003_cookiecreation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiecreation',
            name='description',
            field=models.TextField(default='Add a description to your new creation!'),
        ),
    ]
