# Generated by Django 5.1 on 2024-08-16 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_creation_app', '0001_initial'),
        ('decoration_app', '0001_initial'),
        ('topping_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiecreation',
            name='decoration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='decoration_app.decoration'),
        ),
        migrations.AlterField(
            model_name='cookiecreation',
            name='topping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topping_app.topping'),
        ),
    ]
