# Generated by Django 5.1 on 2024-08-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topping_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
